import re

# NOTE: weasyprint, python-docx, and python-pptx are imported INSIDE each
# function, not at the top of this file. weasyprint needs GTK libraries on
# Windows and often fails to import if they're missing — if it were
# imported at module level, that single failure would break every export
# format (PDF, PPTX, DOCX) the moment this module is loaded, since Python
# fails the whole module's import. Lazy imports keep each format independent.


def export_pdf(markdown_text: str, path: str, title: str = "Research Report"):
    import markdown2
    from xhtml2pdf import pisa  # pure Python (reportlab-based) — no GTK/OS deps, unlike weasyprint

    html_body = markdown2.markdown(markdown_text)
    html = f"""<html><head><meta charset="utf-8"><title>{title}</title>
    <style>
        body {{ font-family: Helvetica, Arial, sans-serif; font-size: 11pt; line-height: 1.5; }}
        h1 {{ font-size: 20pt; }}
        h2 {{ font-size: 16pt; margin-top: 16pt; }}
        h3 {{ font-size: 13pt; margin-top: 12pt; }}
        a {{ color: #2a5db0; }}
    </style></head><body><h1>{title}</h1>{html_body}</body></html>"""

    with open(path, "wb") as f:
        result = pisa.CreatePDF(html, dest=f)
    if result.err:
        raise RuntimeError("xhtml2pdf failed to render the PDF")
    return path


def export_docx(markdown_text: str, path: str, title: str = "Research Report"):
    from docx import Document

    doc = Document()
    doc.add_heading(title, level=0)

    for line in markdown_text.split("\n"):
        line = line.rstrip()
        if not line:
            continue
        if line.startswith("### "):
            doc.add_heading(line[4:], level=3)
        elif line.startswith("## "):
            doc.add_heading(line[3:], level=2)
        elif line.startswith("# "):
            doc.add_heading(line[2:], level=1)
        elif line.startswith(("- ", "* ")):
            doc.add_paragraph(line[2:], style="List Bullet")
        else:
            clean = re.sub(r"\*\*(.*?)\*\*", r"\1", line)
            clean = re.sub(r"\[(.*?)\]\((.*?)\)", r"\1 (\2)", clean)
            doc.add_paragraph(clean)

    doc.save(path)
    return path


def export_pptx(markdown_text: str, path: str, title: str = "Research Report"):
    from pptx import Presentation
    from pptx.util import Pt

    prs = Presentation()

    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title_slide.shapes.title.text = title
    title_slide.placeholders[1].text = "Generated by Multi-Agent Research Assistant"

    sections = re.split(r"\n##\s+", "\n" + markdown_text)
    bullet_layout = prs.slide_layouts[1]

    for section in sections:
        section = section.strip()
        if not section:
            continue
        lines = [l for l in section.split("\n") if l.strip()]
        if not lines:
            continue
        heading = lines[0].lstrip("#").strip()
        body_lines = [
            re.sub(r"\*\*(.*?)\*\*", r"\1", l.lstrip("-*# ").strip())
            for l in lines[1:] if l.strip()
        ]

        slide = prs.slides.add_slide(bullet_layout)
        slide.shapes.title.text = heading[:80]
        tf = slide.placeholders[1].text_frame
        tf.clear()
        for i, bl in enumerate(body_lines[:8]):
            p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
            p.text = bl[:180]
            p.font.size = Pt(16)

    prs.save(path)
    return path
